### PR TITLE
Update README.md, Fix minor other issues

### PR DESCRIPTION
**Pull request by sickboy**
* `npm install -g nodemon` was missing
* createdAt/updatedAt cannot be represented as int
* Implemented collectionId filtering
* Look for process.env.PORT
* Use ISO date
* Enable firstPublishedAt and latestPublishedAt
* Use Collection (Publication) domain for Post url, when available

### CODE REVIEW

**Comment by j3ddesign** [comment]
Hi, Thanks for this! 👍 
I'm going to merge in, despite the CI thinking there's issues (I checked and there dont seem to be, strange)
(You're my first PR <3 )

**Comment by j3ddesign** [comment]
Turns out they did cause a few errors - details at https://travis-ci.org/j3ddesign/medium-graphql/builds/192620899#L272

Going to look into these soon, unless you fancy tackling that too

**Comment by sickboy** [comment]
Awesome, sure thing, no worries @j3ddesign 
You saved my day by setting this thing up :)

Regarding the CI, I guess it's still running TS 2.0, bumping the package.json to 2.1.5 should help address this,
a good idea for the future I think :)

**Comment by j3ddesign** [comment]
ahh ofcourse, I hadn't realised object spread wasn't in until 2.1 - so I'll look into updating that asap!
I'm glad I could help 👍

**Pull request merged**
